schemaVersion: 2.2.0
metadata:
  name: camel-sandbox
  version: 1.0.0
  displayName: Apache Camel Sandbox
  description: Integration sandbox environment for prototyping
  generateName: camel-sandbox
  icon: >-
    https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/java-maven.jpg
  tags:
    - Java
    - Camel
  language: java
attributes:
  controller.devfile.io/storage-type: per-workspace
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:latest
      env:
        - name: QUARKUS_HTTP_HOST
          value: 0.0.0.0
        - name: MAVEN_OPTS
          value: "-Dmaven.repo.local=/home/user/.m2/repository"
        - name: QUARKUS_ANALYTICS_DISABLED
          value: "true"
      memoryLimit: 3Gi
      mountSources: true
      volumeMounts:
        - name: m2
          path: /home/user/.m2
      endpoints:
        - name: http-8778
          targetPort: 8778
        - name: devtools
          targetPort: 8000
        - name: http
          targetPort: 8080
          exposure: public
          secure: false
          protocol: http
        - name: http-8443
          targetPort: 8443
        - name: debug
          targetPort: 5005
          exposure: none
          secure: false
          protocol: tcp
  - name: mqtt
    container:
      image: eclipse-mosquitto
      endpoints:
        - name: http-1883
          targetPort: 1883
          protocol: tcp
      volumeMounts:
        - name: mqtt-conf
          path: /home/user/mqtt-conf
        - name: mqtt-data
          path: /home/user/mqtt-data
        - name: mqtt-log
          path: /home/user/mqtt-log
  - name: m2
    volume:
      size: 1G
  - name: mqtt-conf
    volume:
      size: 1G
  - name: mqtt-data
    volume:
      size: 1G
  - name: mqtt-log
    volume:
      size: 1G
commands:
  - id: install-camel-helm-chart
    exec:
      commandLine: "helm install mqtt-integration-bus /projects/camel-sandbox/openshift/chart"
      component: tools
  - id: uninstall-camel-helm-chart
    exec:
      commandLine: "helm uninstall mqtt-integration-bus"
      component: tools
  - id: start-camel-build
    exec:
      commandLine: "oc start-build mqtt-integration-bus"
      component: tools
  - id: restart-camel-deployment
    exec:
      commandLine: "oc rollout restart deployment mqtt-integration-bus"   
      component: tools 
  - id: install-camel-cli
    exec:
      commandLine: "source ~/.bashrc && jbang trust add https://github.com/apache/camel/ && jbang app install camel@apache/camel"
      component: tools
  - id: install-camel-k8s-plugin
    exec:
      commandLine: "source ~/.bashrc && camel plugin add kubernetes"
      component: tools
events:
  postStart:
    - install-camel-cli
    - install-camel-k8s-plugin
