<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" xmlns:ns0="org.example.Account" xmlns:ns1="org.example.Cart">
    <xsl:output method="xml" indent="yes"/>
    <xsl:param name="orderSequence"/>
    <xsl:param name="account"/>
    <xsl:template match="/">
        <ShipOrder xmlns="org.example.ShipOrder">
            <xsl:attribute name="OrderId">
                <xsl:value-of select="$orderSequence"/>
            </xsl:attribute>
            <OrderPerson>
                <xsl:value-of select="concat($account/ns0:Account/@AccountId, ' - ', $account/ns0:Account/Name)"/>
            </OrderPerson>
            <ShipTo xmlns="">
                <Name>
                    <xsl:value-of select="$account/ns0:Account/Name"/>
                </Name>
                <Address>
                    <xsl:value-of select="$account/ns0:Account/Address"/>
                </Address>
                <City>
                    <xsl:value-of select="$account/ns0:Account/City"/>
                </City>
                <Country>
                    <xsl:value-of select="$account/ns0:Account/Country"/>
                </Country>
            </ShipTo>
            <xsl:for-each select="/ns1:Cart/Item">
                <Item xmlns="">
                    <Title>
                        <xsl:value-of select="Title"/>
                    </Title>
                    <Note>
                        <xsl:value-of select="Note"/>
                    </Note>
                    <Quantity>
                        <xsl:value-of select="Quantity"/>
                    </Quantity>
                    <Price>
                        <xsl:value-of select="Price"/>
                    </Price>
                </Item>
            </xsl:for-each>
        </ShipOrder>
    </xsl:template>
</xsl:stylesheet>