{{- if .Values.build.enabled -}}
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  # Use only the full name (which is the release name) for the BuildConfig name
  name: {{ include "camel-mqtt-export.fullname" . }}
  labels:
    {{- include "camel-mqtt-export.labels" . | nindent 4 }}
spec:
  agentConfig: {}
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      # The ImageStreamTag name should also match the release name for consistency
      name: {{ include "camel-mqtt-export.fullname" . }}:{{ .Values.image.tag }}
  postCommit: {}
  resources:
    requests:
      {{- toYaml .Values.build.resources.requests | nindent 6 }}
  runPolicy: Serial
  source:
    git:
      uri: {{ .Values.build.gitRepoUrl }}
      ref: {{ .Values.build.gitRef }}
    type: Git
    contextDir: {{ .Values.build.contextDir }}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: {{ .Values.build.builderImage.name }}:{{ .Values.build.builderImage.tag }}
        namespace: {{ .Values.build.builderImage.namespace }}
      env:
        - name: MAVEN_ARGS
          value: {{ .Values.build.mavenArgs | quote }}
        - name: MAVEN_OPTS
          value: {{ .Values.build.mavenOpts | quote }}
        - name: MAVEN_S2I_ARTIFACT_DIRS # Directory where build artifacts are placed by Maven
          value: target/quarkus-app  
        - name: S2I_SOURCE_DEPLOYMENTS_FILTER
          value: "app lib quarkus quarkus-run.jar"  
        - name: JAVA_APP_JAR # The name of the runnable JAR within the ARTIFACT_DIR
          value: /deployments/quarkus-run.jar
    type: Source
  triggers: []
{{- end }}
