apiVersion: v1 # Standard Kubernetes API version for ConfigMap
kind: ConfigMap
metadata:
  name: restrictor-config 
data:
  restrictor.xml: |
        <cors>
        <allow-origin>*</allow-origin>
        <ignore-scheme/>
        </cors>
