{{- if .Values.imageStream.enabled -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  # Use only the full name (which is the release name) for the ImageStream name
  name: {{ include "integration-bus.fullname" . }} # Updated helper name
  labels:
    {{- include "integration-bus.labels" . | nindent 4 }} # Updated helper name
spec:
  lookupPolicy:
    local: {{ .Values.imageStream.lookupPolicyLocal }}
{{- end }}
