{{- if .Values.imageStream.enabled -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.imageStream.name }} # Use values from values.yaml
  labels:
    {{- include "camel-mqtt-export.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: {{ .Values.imageStream.lookupPolicyLocal }} # Use values from values.yaml
{{- end }}
