{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  # Use only the full name (which is the release name) for the Route name
  name: {{ include "integration-bus.fullname" . }}
  labels:
    {{- include "integration-bus.labels" . | nindent 4 }}
spec:
  # Removed the explicit 'host' field to let OpenShift assign the default hostname.
  to:
    kind: Service
    # Refer to the Service using its name (which is now the release name)
    name: {{ include "integration-bus.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.route.tlsTermination }}
    {{- if .Values.route.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.route.insecureEdgeTerminationPolicy }}
    {{- end }}
  wildcardPolicy: None
{{- end }}
