apiVersion: v1
kind: Service
metadata:
  # Use only the full name (which is the release name) for the Service name
  name: {{ include "camel-mqtt-export.fullname" . }}
  labels:
    {{- include "camel-mqtt-export.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "camel-mqtt-export.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.appPort }}
      targetPort: {{ .Values.service.appPort }}
    - name: mqtt
      protocol: TCP
      port: {{ .Values.service.mqttPort }}
      targetPort: {{ .Values.service.mqttPort }}
