apiVersion: v1
kind: Service
metadata:
  # Use only the full name (which is the release name) for the Service name
  name: {{ include "integration-bus.fullname" . }} # Updated helper name
  labels:
    {{- include "integration-bus.labels" . | nindent 4 }} # Updated helper name
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "integration-bus.selectorLabels" . | nindent 4 }} # Updated helper name
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.appPort }}
      targetPort: {{ .Values.service.appPort }}
    - name: mqtt
      protocol: TCP
      port: {{ .Values.service.mqttPort }}
      targetPort: {{ .Values.service.mqttPort }}
