apiVersion: v1
kind: Service
metadata:
  name: {{ include "camel-mqtt-export.fullname" . }}-service # Templated name
  labels:
    {{- include "camel-mqtt-export.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }} # Use values from values.yaml
  selector:
    {{- include "camel-mqtt-export.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.appPort }} # Use values from values.yaml
      targetPort: {{ .Values.service.appPort }} # Use values from values.yaml
    - name: mqtt
      protocol: TCP
      port: {{ .Values.service.mqttPort }} # Use values from values.yaml
      targetPort: {{ .Values.service.mqttPort }} # Use values from values.yaml
