quarkus.native.resources.includes=camel/load-generator.camel.yaml,camel/mqtt.camel.yaml,camel/ship-order.camel.yaml
camel.main.routes-include-pattern=camel/load-generator.camel.yaml,camel/mqtt.camel.yaml,camel/ship-order.camel.yaml
quarkus.hawtio.authenticationEnabled = false
quarkus.camel.debug.enabled = true
camel.debug.enabled=true
camel.main.inflightRepositoryBrowseEnabled=true
mqtt.brokerUrl=tcp://localhost:1883
