quarkus.hawtio.authenticationEnabled = false
quarkus.camel.debug.enabled=true
camel.debug.enabled=true
camel.main.inflight-repository-browse-enabled=true
mqtt.brokerUrl=tcp://localhost:1883
rest.api.port=8080
quarkus.native.resources.includes=camel/mqtt.camel.yaml
camel.main.routes-include-pattern=camel/mqtt.camel.yaml
