quarkus.hawtio.authenticationEnabled = false
quarkus.camel.debug.enabled=true
camel.debug.enabled=true
camel.main.inflight-repository-browse-enabled=true
mqtt.brokerUrl=tcp://localhost:1883
rest.api.port=8080
quarkus.native.resources.includes=camel/load-generator.camel.yaml,camel/mqtt.camel.yaml,camel/ship-order.camel.yaml,kaoto-datamapper-3f2390ea.xsl
camel.main.routes-include-pattern=camel/load-generator.camel.yaml,camel/mqtt.camel.yaml,camel/ship-order.camel.yaml
