# Default values for camel-mqtt-export.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # The ImageStreamTag name for your application image
  name: camel-mqtt-export
  # The tag for your application image
  tag: latest
  # Image pull policy
  pullPolicy: Always

mosquittoImage:
  # The image name for the Mosquitto container
  name: eclipse-mosquitto
  # The tag for the Mosquitto image
  tag: latest
  # Image pull policy
  pullPolicy: Always

service:
  # Service type (ClusterIP is common for internal services)
  type: ClusterIP
  # Port for the Camel application
  appPort: 8080
  # Port for the Mosquitto broker
  mqttPort: 1883

route:
  # Enable or disable the Route
  enabled: true
  # Hostname for the Route (optional)
  # host: your-app.your-openshift-domain.com
  # TLS termination type for the Route (edge, passthrough, reencrypt)
  tlsTermination: edge
  # Insecure traffic policy for the Route (None, Allow, Redirect)
  insecureEdgeTerminationPolicy: Redirect # Or Allow, None

build:
  # Enable or disable the BuildConfig
  enabled: true
  # Git repository URL for the source code
  gitRepoUrl: https://github.com/agiertli/camel-sandbox.git
  # Git reference (branch, tag, or commit)
  gitRef: main
  # Context directory within the Git repository
  contextDir: mqtt/mqtt-export
  # S2I builder image details
  builderImage:
    name: openjdk-11-openshift
    tag: latest
    namespace: openshift # Namespace of the builder image
  # Maven arguments for the build
  mavenArgs: "-DskipTests=true package"
  # Maven JVM options for the build (e.g., heap size)
  mavenOpts: "-Xmx2g"
  # Resource requests for the build pod
  resources:
    requests:
      cpu: 1
      # memory: 2Gi # Uncomment and set if needed

# ImageStream definition for the application image
imageStream:
  # Enable or disable the ImageStream
  enabled: true
  # Name of the ImageStream
  name: camel-mqtt-export
  # Lookup policy for the ImageStream
  lookupPolicyLocal: true
